= tumblrが解約できない？！　パスワードが違うと言われる。

tumblrの解約時、パスワードが違うというメッセージが出て解約できないことがある。
ここで求められているのはYAHOOアカウントのパスワードではなく、tumblrのパスワードであるということに注意が必要です。

tumblrのパスワードは初期状態では設定されていないため、解約前に、まずはパスワードを設定します。

tumblrログイン時に『アカウントにログインがありました。』と言うメールを受信するように設定します。届いたメールにはパスワード変更のリンクがありますのでそれを使ってパスワードの変更をしましょう。ログイン用(Yahoo.com)と違うパスワードにすると動きがよくわかりますよ。
 想定通りではありますが、tumblr側で二段階認証してもログイン時には使えませんでした。(解約時には求められましたが)




https://www.hivelocity.co.jp/blog/31543/[Tumblrでブログを作ってみよう！]

また、Google Analyticsを登録しておくと、SEOを行う上で欠かせないウェブマスターツールへの登録も簡単に行えるので、是非登録しておきましょう。

一番印象的なのはフレンドリーURLを使えるという点です。

フレンドリーURL:: 「tumblr.com/blog/123/」という形ではなく「tumblr.com/blog/friendly-url」のような形でURLを設定できる機能のことです。

2つ目はディスクリプションが自動設定になっている点です。 +
デフォルトのエディターで投稿した場合、ディスクリプションは本文の最初200文字が設定されます。内容の分かりやすさが重要なので、この点は自分で編集したいところです。解決策としては、一番最初に伝えたい内容を書き込んでおくということになるでしょう。

：

それを把握した上で、一般的なウェブサイトもですが、まずはGoogle Analyticsとウェブマスターツールを設定し、SEO的な問題点をすぐに察知できる状態を作ることが重要です。

その後に一般公開されているTumblrのテーマを利用したり、自分達で開発を行うなどして、見やすく、使いやすいTumblrを作り上げましょう。有料テーマもありますが、Tumblrには優れた無料テーマがいくつも用意されていますので、そちらを使ってもよいかもしれません。


















