= Memo: 2017-10-11
:lang: ja
:encoding: utf-8
// :doctitle: これがドキュメントタイトルになります。
// :description: 文書の説明を書きます。metaタグのdescriptionに設定されます。
// :keywords: カンマ区切りでキーワードを書きます。metaタグのkeywordsに設定されます。
// :title: titleタグに設定されます。
// :docinfo: shared
// :docinfodir: meta
:sectids!:
:linkcss:
:hardbreaks:


== ドライブレコーダーが欲しい。

// ユピテル フルマップレーダー探知機 W50 3年保証 GPSデータ13万6千件以上 小型オービスレーダー波受信 OBD2接続 GPS/一体型/フルマップ表示/静電式タッチパネル
// ユピテル(YUPITERU)
// 価格￥ 19,800(2017/10/11 00:40時点)
// 発売日2017/03/27
// 商品ランキング342位
// 
// 
// W50はユピテル創業50周年記念モデルで、2017年最上位モデルのGWR303sdから無線受信機能を外した代わりに7000円も安いお買い得モデルです。
// 
// 無線受信機能が外されていることを心配する方もいるかと思いますが、ハッキリ言って滅多に役に立ちません。
// 
// 今や警察無線はデジタル化されて内容を聞くことはできず、工事現場で使用されているトランシーバーの電波を取締無線と勘違いして警告してくることの方が多いぐらいで、僕は無線受信機能が付いているレーダー探知機であっても警告をオフにしています。
// 
// そして、これ以外の機能は最上位のGWR303sdと一緒ですから、非常にコスパが高い。なので1台目としてオススメです。














ネズミ取りの方式
　|-- レーダー式
　|-- ステルス式
　`-- 光電管式


エスティマとノートにはHDDナビが付いているのでナビは不要。
ドラレコまたはレーダー探知機を付けたい。

優先順位
　ドラレコを優先する。
　これから冬になるので運転時のリスクが増えるため。
　自分が起こさなくても、最悪もらう可能性もある。

　順番
　　ノート
　　タント
　　エスティマ

　レーダーは来春を目安に付けたい。
　冬は遠出しないので貯めに徹する。


ところで予算は？
どんな種類のがある？
おすすめは？


=== 選ぶポイント

. LED信号機に対応していること。
	* 29fpsや27.5fpsなどのフレームレートで撮影できるモデルを探す。
. 昼でも夜でもナンバープレートがしっかり映ること。
	* キーワード: フルHD、HDR（あるいはWDR）
. 耐久性の高い microSD カードを使うこと。

. 水平画角が「108°」以上であること。


電気の周波数の関係上西日本では60Hz、東日本では50Hzになっています。LEDはこの周波数に合わせて西日本では1秒間に120回・東日本では100回点滅しています。1秒間の間の半分は点灯していますが、半分は点灯していないことになります。

ドライブレコーダーは一般的なフレームレートは30fpsのものが多く、周波数の倍数になってしまいます。そのため、特に西日本では撮影のタイミングが周波数の整数倍と一致した場合に、信号が消えている状態を撮影することになってしまいます。



コムテック
ZDR-012
200万画素の高画素センサーを搭載し、フルHD画質での記録に対応した高画質モデル。この価格ながらHDR/WDRにも対応している。背面液晶は2.3型で、撮影した映像のディテールをきめ細かく確認できる。Gセンサーによる自動保存機能やLED信号の記録にも対応。急加速や急減速時に警告するドライブサポート機能も搭載する。 



ユピテル
DRY-WiFiV3c
コンパクトなボディーに300万画素の高画素センサーと1.5型液晶を搭載したプレミアムモデル。記録画質はフルHDに対応。一番の特徴は、本体にWi-Fi機能を搭載しており、手持ちのスマホからコントロールできること。記録した映像を専用アプリで表示したり、映像のバックアップがワイヤレスでできる。 









参考

https://kakakumag.com/car/?id=10515[《2017年》人気のおすすめドライブレコーダーはこれ！選び方のポイントは3つ - 価格.comマガジン]












KIOKUNOMORI （記憶の森）

Facebookページがあるのでそこを見てイメトレしておく。















谷中レトロカメラ店の謎日和 フィルム、時を止める魔法 (宝島社文庫 『このミス』大賞シリーズ)












== 参考

* https://ameblo.jp/akishim/entry-11888170771.html[プロが教えたくない「結婚式の撮り方」～準備と設定まるわかり！]

* http://www.takac-photo.com/entry/2016/06/15/080000[結婚式に持って行くカメラとレンズについて考える]

* http://www.takac-photo.com/entry/2016/06/22/080000[単焦点レンズ2本でウェディングフォトにチャレンジしてきた【2016.6.17〜20】]

* http://www.tedium-life.com/entry/2016/11/12/190000[【デスクワークの方必見!!】一瞬で、しかし劇的に効く!!　最強フィジカルトレーナーが教える、凝り固まった身体を正しい方向へ持っていく方法]

* http://blog.goo.ne.jp/how_to/e/3a6ec3071ce6196bfb0da9bd46125504[モジュール一覧 - goo ブログの使い方]












== blog

記録をgooブログで付けてみる。
（年内中にアドバンスにグレードアップしたい）

CSSのカスタマイズはどこまでできるか。
使えるHTMLの種類は少ないが、まぁ、気軽に。
ひとまずCSSカスタマイズできるテンプレートにしてみて、どのくらいいじることができるか試してみる。

収益は目指さない。
ターゲットは将来の自分？
日々の記録と写真が載せられればまず良しとしよう。

どこでやるかというのも大事だが、形ばかり気にしていつまで経っても踏み出さないのはどうかと。

独自ドメインもstyleタグもscriptタグも使えない。
プログラムのソースを載せておきたいというのは厳しいかもしれない。
そんなに載せないと思うけどね。

...もしかしてlinkタグは使える？
ヘルプにはスクリプトタグは禁止とあるが、そのほかどのタグが禁止されているのかは記載がない。

カテゴリはある。
タグはない。

nmk2k

Keywords:
Rollei35T, NATURA 1600
プログラム（ASP.NET、VBScript、JScript、Java）
プログラムのパーツを貼り付けて残しておきたい。
似たような案件をやるときに、そこを見ればコピペで作れる、あるいは要点を思い出せるように。
たとえば、あるフォルダのパスを指定して、その配下のファイルを再帰で処理するようなスクリプト。とか。


まとめておきたいもの

* 運動会のカメラとレンズ
	** 検討段階
	** 35-100mm/F2.8にしたこと
	** 考察
* 金魚の飼い方
	** 土沢まつりでもらってきた、でめきん
* かぶとむしの飼い方
	** オス（幼虫）購入～メス（成虫）購入～オス羽化～結婚・産卵～卵からかえる
	** ケース買ったり。















== CSS編集機能

先ほどgooブログでは、CSS(スタイルシート)の編集ができる新機能をリリースいたしました。
編集できるテンプレートは、3種類。現行テンプレート「ブルー」を基にした「カスタムブルー」、「メタル」を基にした「カスタムメタル」、そしてテンプレート構造が全面的にCSSに依存している「カスタムフリー」の3種類です。
→CSSって何だ？って言う人は。まずはこちら（CSSとは？）をご参照ください。

「カスタムブルー」::
パソコン画面の大きさに合わせた可変型（リキッド型）の構造になっていること。画面の「色」や文字「サイズ」などを自由に設定できます。編集方法は解説（→CSSを使ってみよう）をご参照ください。

「カスタムメタル」::
テンプレートの幅が「固定」されている構造になっていること。
ヘッダー部分に写真などを貼ってテンプレートを飾ってもらうにはうってつけのテンプレートになっています。

「カスタムフリー」::
CSS中級者から上級者の方が対象になっているテンプレートです。
0（ゼロ）からCSSを編集したい！とお考えのブロガーの方にはお奨めのテンプレートです。

CLアドバンステンプレート::
2カラム、3カラムの切り替えや、モジュールの配置を変更できるほか、ブログパーツなどのオリジナル要素をサイドバーや記事エリアに追加することができる「カスタムレイアウトテンプレート」に、CSSの編集機能を追加したテンプレートです


