= Note for 3rd week of Oct. 2017
:lang: ja
:encoding: utf-8
// :doctitle: これがドキュメントタイトルになります。
// :description: 文書の説明を書きます。metaタグのdescriptionに設定されます。
// :keywords: カンマ区切りでキーワードを書きます。metaタグのkeywordsに設定されます。
// :title: titleタグに設定されます。
// :docinfo: shared
// :docinfodir: meta
:sectids!:
:linkcss:
:hardbreaks:



== 読書録

「なぜ」と「どうして」を押さえて
しっかり！　まとまった！　文章を書く

朝日新聞編集担当補佐　+++<ruby>前田安正<rp>（</rp><rt>マエダヤスマサ</rt><rp>）</rp></ruby>+++ ・著


サンプルを読んだ限りでは、読みやすい印象。


5W1Hを意識する

When	いつ
Where	どこで
Who		誰が
What	何を
Why		なぜ
How		どうのように
-		どうした

中でも5番目のWであるWhy、「なぜ」「どうして」を掘り下げて考える。
文章が続かないと思っている理由は、4Wで止まっているからということが多い。

文章はWhy（「なぜ」「どうして」）で肉付けする。


報告書に必要な要素は、①目的、②データ、③分析、④課題、⑤展望です。

. 目的
. データ
. 分析
. 課題
. 展望


意見を書くときには、客観的な裏付けを盛り込む。
聞いた話を鵜呑みにせず、資料などに当たって確認を取る。
正しい情報を増やし、描写をより具体的にする。


観察眼を鍛える。
書くべき対象をよく観察して、一つ一つ丁寧に書く。

観察する癖をつければ、書くべきものも見えてくる。

「書く」ということ
　＝必要な部分を選択すること
　＝不必要なところを切り捨てること

一部始終を再現する必要はない。
「書きたい」部分を絞り込む。
　⇒文章の核にする。

話にふくらみを持たせるには、色や匂いなどの五感も拾う。

「大切だ」「大事だ」という思いを書くためには、経験した事柄を掘り下げていく。


観察すべきことは多い。

* 色、匂い、音などの周囲の様子
* 気温、天気の具合、移り変わり
	** 寒かったのか、暑かったのか。
	** 晴れなのか、曇りなのか、雨なのか。
* 人数は？　一人だったのか、複数人だったのか。
* 仲間の行動や言動、会話の内容













== いとこの結婚式撮影について考えてみた

// Note: 
// 
// * プロには依頼している模様。
// * 自分たちは撮影を頼まれたわけではない。
// * なのであまり出しゃばらないように、また必要以上に気負わず立ち振る舞う。
// * こちらの人数は自分も含めて3人。
// * 結婚式や披露宴のプログラム、席次などの式に関することは、当日にならないと分からない。
// * 披露宴の席次は、おそらく親族なので高砂からは遠いと思われる。ただし、会場の広さも分からないのでどの程度の距離になるかは、まったく分からない。

今月、福島で行われるいとこの結婚式に招待されている。
写真撮影を頼まれたわけではないが、せっかくなので写真をプレゼントしたいと思った。
ほかのいとこたちからも快く協力するとの回答がもらえたので、自分も含めて3人で撮影に臨むことにした。

ちなみに、当日の撮影はプロのカメラマンにお願いしている模様。
こちらは失敗しても大丈夫なので、必要以上に気負わず、出しゃばり過ぎないように立ち振る舞いたい。
そして、（まぁそもそも勝ち負けの話ではないが）品質ではプロに勝てないので、スピード仕上がりを目指す。



=== 機材選定

機材の候補は次のとおり。

* LUMIX DMC-TX1
* PowerShot G7 X Mark Ⅱ
* K-30 ＋ smc PENTAX-DA 18-135mmF3.5-5.6ED AL[IF] DC WR ＋ AF540FGZ


==== LUMIX DMC-TX1

ズーム倍率重視の1インチセンサーのコンデジ。
2000万画素、レンズの焦点距離（35mm判換算）と開放F値は、f=25-250mm/F2.8-5.9。

私が使う予定。4Kフォトで動画＋静止画を狙う。
4Kフォトにすることで焦点距離が 25-250mm から 37-370mm に伸びる。
結婚式撮影では標準～望遠域をメインで使うだろうから、コレは便利。

AF速度が動画のフレームレート（30fps）に合わせた仕様にダウンするようだが、自分以外にも撮影者がいるので良しとする。
望遠端の開放F値がF5.9と暗いのが気にかかるが、ISO感度を上げるなり、シャッター速度を落とすなりして臨機応変にやりたい。

当初は手持ちのGM1Kに、レンタルの明るい望遠レンズ（35-100mm/F2.8）を組み合わせることを考えた。
しかし、自分の子供（3歳半児＆魔の2歳児ｗ）の面倒を見る必要もあり撮影に専念できないため、最終的にコンデジにした。


==== PowerShot G7 X Mark Ⅱ

明るいレンズで、TX1と同様の1インチセンサーのコンデジ。
2000万画素、レンズの焦点距離（35mm判換算）と開放F値は、f=24-100mm/F1.8-2.8。

カメラに詳しくなくても簡単に使えると思い、PowerShot G7 X Mark Ⅱを選択。
よりコンパクトな G9 X と悩んだが、レンズの開放F値を優先してこちらにした。
いとこに使ってもらう予定。

望遠端が短いが、プログレッシブファインズームという劣化が少ないデジタルズームを使うことで 200mm 相当までズームができるようになる。
これでも望遠側が足りなければ、あとは足を使って稼いでもらう。

// http://cweb.canon.jp/pls/webcc/WC_SHOW_CONTENTS.EdtDsp?i_cd_pr_catg=006&i_tx_contents_dir=/e-support/faq/answer/digitalcamera/&i_tx_contents_file=87352-1.html&i_fl_edit=1&i_tx_search_pr_name=&i_cd_qasearch=Q000087352[被写体をもっと拡大して撮影したい (PowerShot G7 X Mark II）]


==== K-30 ＋ smc PENTAX-DA 18-135mmF3.5-5.6ED AL[IF] DC WR ＋ AF540FGZ

撮影者本人が持っているデジタル一眼に、私が持っているストロボ（AF540FGZ）を装備させることにした。
レンズは smc PENTAX-DA 18-135mmF3.5-5.6ED AL[IF] DC WR にするらしい。

35mm判換算で 27-200mm。
こちらも望遠が不足気味なので足で稼いでもらい、それでも足りなければトリミングで仕上げる。

ほかの2台よりセンサーが大きいし、ストロボも装備するので、仕上がりに期待したい。


=== まとめ

「おめでとう」という気持ちを第一に、必要以上に気負わず、周りの迷惑にならないように立ち振る舞う。
そして、料理もお酒も楽しみつつ、喜んでもらえるような写真を撮りたい。















== 気付いたらキヤノンから PowerShot G1 X Mark III が発表されていた

キヤノンから PowerShot G1 X の最新版 Mark III の発売が発表されていた。
発売予定は2017年11月下旬の模様。

レンズ交換をする気がなくてズーム倍率も気にならない人にとっては、これ以上ない全部入りの最強カメラだと思う。
ただし、価格も最強。カメラのキタムラネットショップでは税込み￥123,930。
さすがに手が出せない。

子供の成長記録を撮るには良さそうなのだが……。

製品の特長は次のとおり。

* APS-Cサイズ相当のCMOSセンサー（約22.3×14.9mm）
* 3倍ズームレンズ。35mm判換算 24-72mm/F2.8-5.6
* 画像処理エンジンは最新の DIGIC 7
* 像面位相差AF「デュアルピクセルCMOS AF」を搭載
* 防塵防滴構造
* バリアングル液晶モニター。しかもタッチパネル。3型、約104万ドット
* EVF搭載。0.39型、約236万ドット、有機EL
* 意外と軽い。約399g（電池及びメモリーカード含む）
* 意外と小さい。約115.0 × 77.9 × 51.4mm
* Wi-Fi/NFCに加え、Bluetoothによる常時接続が可能
* USB充電可能


=== 参考

* カメラのキタムラ ネットショップの商品ページ
* デジカメ Watch のニュースページ

















TX1の焦点距離（ステップズームで選択できる値）別に開放F値を調べる。

|===
|焦点距離 |開放F値

|25
|F2.8

|28
|F3.0

|35
|F

|50
|F

|70
|F

|90
|F

|135
|F

|200
|F

|250
|F5.9

|===


Sample: プロレスでスポットライトを浴びた人物を撮る
ISO800 1/125 F5.9
-2 + 7 + 5 = LV10












== gooをやめてJUGEMにいく

JUGEMのカスタマイズはどこまでできる？
gooでいいかなと思っていたが、スマホから見たときに広告（フローティング？）が表示された。
このタイプの広告は邪魔くさいのでやめたい。

次のサイトは、スマホで見たときに広告表示される？
http://mrhk.jugem.jp/?eid=156

gooの有料版は月200円、JUGEMは月300円。
（年￥2,592 vs ￥3,888）
JUGEMはスマホ版からも広告が消える。gooは何もいじれない。
100円ぐらいの差ならJUGEMにしてもいいんじゃない？

テンプレート、HTML、CSSがどこまでカスタマイズできるかは確認する。

カテゴリーとテーマがある。
カテゴリーはユーザーが自由に作成可能。
テーマはJUGEMがあらかじめ設定したものの中から選ぶ。


=== JUGEMサポート

* http://faq-jugem.jugem.jp/?eid=60[サイトマップの作成手順について。 | JUGEM よくある質問集 FAQ]
* http://faq-jugem.jugem.jp/?eid=62[無料版に表示される広告の種類について教えてください。 | JUGEM よくある質問集 FAQ]
* http://faq-jugem.jugem.jp/?eid=111[テンプレートを編集したい。 | JUGEM よくある質問集 FAQ]
* http://faq-jugem.jugem.jp/?eid=233[テンプレートのコピーライト表記やJUGEMバナーは削除してもよいですか？ | JUGEM よくある質問集 FAQ]




















日常点検における点検対象装置の検索について。

当日点検対象項目を持つ装置が属するフロア、工程を選択させ、最終的に装置IDを入力する。









